export const ActionTypes = {
    FETCH_COUNCILLORS: 'FETCH_COUNCILLORS',
    FETCH_COUNCILLORS_COMPLETE: 'FETCH_COUNCILLORS_COMPLETE',
    FETCH_COUNCILLORS_ERROR: 'FETCH_COUNCILLORS_ERROR',
    FETCH_COUNCILS: 'FETCH_COUNCILS',
    FETCH_COUNCILS_COMPLETE: 'FETCH_COUNCILS_COMPLETE',
    FETCH_COUNCILS_ERROR: 'FETCH_COUNCILS_ERROR',
    FETCH_AFFAIRS: 'FETCH_AFFAIRS',
    FETCH_AFFAIRS_COMPLETE: 'FETCH_AFFAIRS_COMPLETE',
    FETCH_AFFAIRS_ERROR: 'FETCH_AFFAIRS_ERROR',
};
